### ISSUE TITLE
Recursion Problems

### ISSUE THREAD

**Issue by theexplorist** [sahilbansal17/Competitive_Coding#101]
Hey, i want to add some recursion problems and their solutions ,can you assign me that task ?

**Comment by sahilbansal17** [comment]
@theexplorist Please specify the problems here as [Task list](https://blog.github.com/2014-04-28-task-lists-in-all-markdown-documents/).

**Comment by theexplorist** [comment]
I want to work on counting the number of mazepaths possible from start to destination in a maze!

**Comment by sahilbansal17** [comment]
State the problem more precisely defining the maze.

**Comment by theexplorist** [comment]
there is a n*n maze where suppose there is start point and an end point.The problem will be divided into two parts:-
1.we can move only vertical or horizontal.
2.we can move vertical,horizontal,diagonally.

then we have to count the number of possible paths in both the cases.

**Comment by ramitsawhney27** [comment]
Modify this so that you can start anywhere from the leftmost column and end either at the middle(if odd) or middle two(if even) points on the rightmost column.

**Comment by theexplorist** [comment]
what is odd or even in maze when maze is n*n ! And you want destination point to vary!

**Comment by theexplorist** [comment]
In implementation i am not actually making a 2d grid , i am just making a function f(current column,current row, dest column, dest row).

**Comment by ramitsawhney27** [comment]
If n is even then you have 4 rows and 4 columns. In this case you must end at (1,3) or (2,3) [0 based indexing]. If n is odd then you end at only (1,2). I hope this is clear.

**Comment by theexplorist** [comment]
The code is complete , i have used backtracking in it, now what is the procedure to pull request ?

**Comment by ramitsawhney27** [comment]
You can count the number of paths using DP/memoization as well. Please add that to the solution as well.

**Comment by sahilbansal17** [comment]
@theexplorist Send a PR mentioning the issue no. Kindly don't send PR from master branch directly, create a new branch, commit the changes and then send a PR, so that its easier to sync changes later. Follow the [github workflow](https://github.com/sahilbansal17/Competitive_Coding/wiki/GSSoC#github-workflow) and the [general guidelines](https://github.com/sahilbansal17/Competitive_Coding/wiki/GSSoC#general-guidelines--expectations-from-you).
