### ISSUE TITLE
Subsequences of string questions

### ISSUE THREAD

**Issue by Aashu24** [sahilbansal17/Competitive_Coding#102]
Given a string, the problem is to generate all possible subsequences of that given string. I will be coding this in Java. I will like to give the following three solutions to this problem : 

- [x] Return all subsequences of the String (Recursive approach)

- [x] Longest repeated subsequence problem via top down DP

Please assign these three tasks to me so that I can start working on them as soon as possible.

**Comment by ramitsawhney27** [comment]
Just solve the first one, the other 2 are redundant. Along with this solve the longest repeated subsequence problem via **top down DP**, not bottom up.

**Comment by Aashu24** [comment]
@ramitsawhney27 Okay! I will start working on them
