### ISSUE TITLE
Modified LCS Problem

### ISSUE THREAD

**Issue by ramitsawhney27** [sahilbansal17/Competitive_Coding#103]
Given:
n strings of length m consisting of only 'a' and 'b' as characters.
a hidden string of length m (this can be any string consisting of 'a' and 'b')

Tasks:
1. Calculate the **least** value of the Longest Common Subsequence of the given n strings and the hidden string.

Sample:
2 given strings:
ab
ba

The hidden string can be (aa,ab,ba,bb). The LCS for all cases is equal to 1. Hence the answer is 1.

2 given strings:
aa
bb

The hidden string can be anything, the LCS will always be 0. Hence the answer is 0.

3 given strings:
aabb
abab
baab

Answer: 2

**Comment by mohitj27** [comment]
I want to work on this problem. Please assigned to me this code

**Comment by mohitj27** [comment]
but i work on this issue this is against policy somebody else solve the problem before my given time gets over

**Comment by mohitj27** [comment]
okk
