### ISSUE TITLE
CrossWord 

### ISSUE THREAD

**Issue by Sandip75** [sahilbansal17/Competitive_Coding#105]
Please assign it to me.

**Comment by sahilbansal17** [comment]
@Sandip75 Please describe the problem. If it is already taken up and/or similar to #101 , you need to take up something new.

**Comment by Sandip75** [comment]
It's similar I will find other Problem.

**Comment by Sandip75** [comment]
![image](https://user-images.githubusercontent.com/29688336/42045457-362ec16a-7b19-11e8-9359-533ebec611d9.png)


Here I find other Problem ( Crossword ) 
1. Where I am given an array of ( n * m ) size. 
    In array  0 and 1 Values are set. If we get 0 its means char can be placed and 1 Its must be empty.
 2. We have an array which contains string values 

We have to place array string values in the first array.

**Comment by ramitsawhney27** [comment]
@Sandip75 where did you find this question?

**Comment by Sandip75** [comment]
college coding competitions in DTU last year

**Comment by Sandip75** [comment]
@sahilbansal17 @ramitsawhney27 
should I do or Not?

**Comment by sahilbansal17** [comment]
@ramitsawhney27 Please confirm.

**Comment by ramitsawhney27** [comment]
Go ahead, good luck! :)
