### ISSUE TITLE
STL implementations

### ISSUE THREAD

**Issue by sahilbansal17** [sahilbansal17/Competitive_Coding#106]
- Explaining the **most common** operations for STL implementations of each of the following data structures along with the time complexities involved for the operations, write well commented code following the [standards](https://github.com/sahilbansal17/Competitive_Coding/wiki/Coding-Standards). 
- Take inputs from user wherever required via good prompts.

Make changes in the appropriate linked files. 

- [x] [Stack](https://github.com/sahilbansal17/Competitive_Coding/blob/master/Data%20Structures/Stacks/stl_stack.cpp)
- [x] [Queue](https://github.com/sahilbansal17/Competitive_Coding/blob/master/Data%20Structures/Queues/stl_queue.cpp) 
- Height-balanced trees:
    - [x] [Set](https://github.com/sahilbansal17/Competitive_Coding/blob/master/Data%20Structures/Trees/stl_set.cpp) 
    - [x] [Map](https://github.com/sahilbansal17/Competitive_Coding/blob/master/Data%20Structures/Trees/stl_map.cpp) 
- [x] [Priority-Queue](https://github.com/sahilbansal17/Competitive_Coding/blob/master/Data%20Structures/Heaps/stl_priority_queue.cpp) 

Each of the 5 are separate issues with the category **cakewalk** and can be taken up only by different people. The first one to claim below a specific sub-task will be assigned for it.

**Comment by sourabh1031** [comment]
@sahilbansal17 I would like to work for stack and queue both

**Comment by sahilbansal17** [comment]
@sourabh1031 Sure, you should start working.

**Comment by lavishsaluja** [comment]
Working on Priority-Queue!

**Comment by shreyateeza** [comment]
@sahilbansal17 I want to work on Height-balanced trees.

**Comment by sourabh1031** [comment]
@sahilbansal17 can i work on height balanced trees as there has not been any pr made so far

**Comment by shreyateeza** [comment]
@sourabh1031 Please go ahead as currently I am not working on this issue. :)

**Comment by sourabh1031** [comment]
@sahilbansal17 i am working on remaining two
