### ISSUE TITLE
Add Divide & Conquer algorithms

### ISSUE THREAD

**Issue by sahilbansal17** [sahilbansal17/Competitive_Coding#11]
Implement the following algorithms [take reference from MIT OCW 6-046 Spring 2015 Lectures] :
- [ ] Weighted Job Scheduling  [Lecture 1]
- [x] Closest Pair of Points [Related to Problem Set 1] 
- [x] Convex Hull [Lecture 2]
- [x] Median Finding [Lecture 2]
- [ ] Strassen's Algorithm for Matrix multiplication [Recitation] 

Each of them will be treated as a separate issue. 
As you finish either of them, tick it above and send a PR mentioning this issue number.

**Comment by dhairyabaweja** [comment]
I would like to contribute!!

**Comment by pritamnegi** [comment]
Can i work on weighted job scheduling??

**Comment by sahilbansal17** [comment]
@pritamnegi There is already an PR for it as clearly visible above. Convex Hull and Closest Pair of points are left.

**Comment by pritamnegi** [comment]
ok will try to work on convex hull

**Comment by pritamnegi** [comment]
Ok then working on convex hull

**Comment by sahilbansal17** [comment]
Closest pair of points problem is yet to be claimed.

**Comment by pritamnegi** [comment]
I would like to work on closest pair of points. Can i work on it??

**Comment by sahilbansal17** [comment]
@pritamnegi Sure, go ahead.

**Comment by Anjali2901** [comment]
Can i work on Strassen's Algorithm for Matrix multiplication?

**Comment by sahilbansal17** [comment]
@Anjali2901 Yes, sure.

**Comment by Anjali2901** [comment]
Strassen's Algorithm for Matrix multiplication Up for Grab , I couldn't work on it .

**Comment by shivhek25** [comment]
@sahilbansal17 I would like to work on weighted job scheduling algorithm.

**Comment by sahilbansal17** [comment]
@shivhek25 One issue at a time.

**Comment by pritamnegi** [comment]
I am unable to figure out code for Closest pair of points. It's up for grab
