### ISSUE TITLE
Floyed Warshall(finding all possible shortest path of a graph) Algorithm

### ISSUE THREAD

**Issue by jstjyoti** [sahilbansal17/Competitive_Coding#114]
Can I work on Floyed Warshall(finding all possible shortest path of a graph) Algorithm?

**Comment by sahilbansal17** [comment]
Yes, go ahead.

**Comment by sahilbansal17** [comment]
Issue #62 already existed for the same. You should not create new issues if one already exists.

**Comment by jstjyoti** [comment]
okay I am closing this and joining that issue. Kindly assign that to me.

**Comment by jstjyoti** [comment]
Hello mentor,
Thank you for giving us a glimpse of open source contribution and git hub.

As instructed by github certificates to all the participants will be sent
by mentors. So I want to ask you a few things about certificate.
1.Will the certificate be given to all the participants?
2.Will the name of project be there on the certificate?
3.Will the certificate have any tag of Google or only Girlscript?

Hope for a fast reply.

Regards,
Jyoti Mishra (@jstjyoti).

**Comment by sahilbansal17** [comment]
Hi @jstjyoti,
It was great to see a good amount of contribution from your side. 

We are not responsible for certificates, they will be provided by GSSoC organizers, I guess it will be provided to all the participants. I am not sure about the other details, so you can confirm rest of the things by asking on the slack channel.
