### ISSUE TITLE
kadane's algorithm implementation

### ISSUE THREAD

**Issue by frost-queen** [sahilbansal17/Competitive_Coding#115]
Finding the maximum contiguous sum in an array.

**Comment by frost-queen** [comment]
Can i work on this issue?

**Comment by sahilbansal17** [comment]
Yes, go ahead.

**Comment by sahilbansal17** [comment]
Make the followibg modification:
1. If there are more than two segments with maximum contiguous sum, find the one with smaller length.
2. To break ties within the smallest maximum sum segments, choose the one with lowest index.

Do this with the best possible time and space complexities.

**Comment by sahilbansal17** [comment]
@frost-queen Please confirm if you are still working, two days have gone by.

**Comment by frost-queen** [comment]
Yes I am working . I will be submitting the PR soon
