### ISSUE TITLE
Lazy Propagation in Segment Tree

### ISSUE THREAD

**Issue by h-sinha** [sahilbansal17/Competitive_Coding#116]
Performing range update in segment tree using lazy propagation

**Comment by h-sinha** [comment]
Working on this issue

**Comment by h-sinha** [comment]
@sahilbansal17 should I include the complexity of segment tree formation in this file too?

**Comment by sahilbansal17** [comment]
@h-sinha Just include explanations for all that is not in the previous **Segment Tree** code.
