### ISSUE TITLE
Sliding window algorithm

### ISSUE THREAD

**Issue by shivhek25** [sahilbansal17/Competitive_Coding#118]
I would like to work on the sliding window algorithm.
I'll be taking up the problem of calculating the max consecutive sum in an array such that it is less than or equal to an entered number.

**Comment by lavishsaluja** [comment]
@shivhek25 What is the entered number here? (the length of that sub-array?) Also Isn't this similar to https://github.com/sahilbansal17/Competitive_Coding/issues/115

**Comment by shivhek25** [comment]
It can be any random number, for which the max consecutive sum should be less than or equal to it.
Now, thats different because that algorithm involves positive and negative numbers to be calculated for max condition. Here, a dp technique will be implemented to find that particular consecutive set of elements which will have sum less than or equal to the entered number.
