### ISSUE TITLE
Heap data structure

### ISSUE THREAD

**Issue by sourabh1031** [sahilbansal17/Competitive_Coding#124]
@sahilbansal17  @ramitsawhney27 I want to work on this as a whole including heap sort please assign it to me

**Comment by sourabh1031** [comment]
@sahilbansal17 okay can i do implementations of heap data structure

**Comment by sahilbansal17** [comment]
The following things can be implemented: 
- [ ] Insertion, Deletion, Traversal along with well explained complexities
- [ ] Building heap from an array with the complexity of `O(N)` along with proof complexity.
- [ ] An efficient linear time algorithm for merging two binary heaps. 

First two task are for 10 points in total and last one is for 20 points. 
@ramitsawhney27 Please make modifications if necessary.

**Comment by sourabh1031** [comment]
Can i take all the issues ?

**Comment by sahilbansal17** [comment]
Yes sure.
