### ISSUE TITLE
Warmup Task - GSSoC

### ISSUE THREAD

**Issue by sahilbansal17** [sahilbansal17/Competitive_Coding#13]
Hi all, 

This is the warmup task for you to just solve a few problems and add your solutions right here.

We can follow a common website [[Codeforces](https://www.codeforces.com)] to find problems for this task. 
- Go to the **[Problemset](https://codeforces.com/problemset)** section of the site. 
- Find a tag(topic) of your interest (e.g. *binary search*) and click on it. 
- To sort the problems in increasing order of difficulty (can be estimated by the no of people who solved that problem), click on the last column heading which shows a ✅. The numbers in that column denote the no of people who have solved the problem. 
- Solve atleast one problem in this topic and add your solutions here via a pull request mentioning the issue number(#13) in the description. The solutions are to be added in [this](https://github.com/sahilbansal17/Competitive_Coding/tree/master/Problem%20Solutions/Codeforces/Tags) folder. 

For reference, check some solutions already in this repo on **Graphs** [here](https://github.com/sahilbansal17/Competitive_Coding/tree/master/Problem%20Solutions/Codeforces/Tags/graphs), corresponding to which problems can be found [here](https://codeforces.com/problemset/tags/graphs?order=BY_SOLVED_DESC).

For any kind of discussions, either comment here or write in the Slack channel.

**Comment by mohitj27** [comment]
we have to find hard question and then solve it or solve any question irrespective of hard or easy or moderate type of difficulty.

**Comment by sahilbansal17** [comment]
@mohitj27 You can solve question of any level of difficulty, I just told to sort in increasing order of difficulty for convenience, also you can choose any topic. 
But, try to write good readable code.
