### ISSUE TITLE
Edit distance problem

### ISSUE THREAD

**Issue by Aashu24** [sahilbansal17/Competitive_Coding#132]
Given two strings, we have to find the minimum number of operations (edits) that can be performed on the strings to make them both equal. The following operations can be performed on the strings:
1. Inserting a character
2. Removing a character
3. Replacing a character with some other character

I would like to work on this problem in Java. Please assign it to me.

**Comment by sahilbansal17** [comment]
Modify this problem as follows:
Convert the string into a palindrome with the minimum **COST**. You are allowed to do all the three operations mentioned above.
- Operation *i* takes *i* units of cost, i.e. inserting a character would take 1 unit of cost. 

for e.g.: **abddea** can be converted to **abeddeba** using two insertions (cost 2), or to **abddba** using one replace (cost 3), ... 
So, you have to output the minimum cost 2 and the palindrome formed.

**Comment by Aashu24** [comment]
@sahilbansal17 Okay!

**Comment by Joycevarg** [comment]
I would like to work on this issue.Ping me if it is ever again going to be free.
