### ISSUE TITLE
Fractional Knapsack(Greedy Algorithm)

### ISSUE THREAD

**Issue by jstjyoti** [sahilbansal17/Competitive_Coding#133]
### **Fractional Knapsack Problem**:
- We are given n number of Objects and a Knapsack(bag) of capacity 'm'.
- each object has different weights 'w_i_'  and profit 'p_i_'
- if a fraction 'x_i_' of object i is placed into the knapsack then profit earn is 'p_i_*x_i_' 
Our Objective is to fill the knapsack such that the profit is maximum.

I want to solve this problem using Greedy algorithm.

**Comment by ramitsawhney27** [comment]
1. Give a proper proof as to why the greedy solution works here and not for 0-1 Knapsack problem.
2. Modify this so you take a value v[i] for each item i that acts as a multiplier to the profit as:
for fraction x_i of object i, the profit will now be: p_i * x_i * (v_i * (x_i)^2). Also, show that if the greedy solution works for this. if not, solve using DP.

**Comment by jstjyoti** [comment]
Greedy approach gives a solution for optimization Problem and always makes a choice which seems best at that moment and adds it to current subsolution . Final Output is optimal having maximum profit .
Greedy algorithm don't always yield optimal solution but,
when they do,they are usually the simplest and most efficient algorithms available.

the problems in fractional knapsack is to 
- n items 
- fraction of item i is taken to maximize profit unless the bag is full. Globally optimal choice is to take item with largest profit as p_i*(weight of object/weight remaining) and Greedy choice property for maximizing profit holds.

Dynamic Programming can solve Subproblems as well as overlapping Subproblems and finds a best  solution by solving subproblems.

Fractional Knapsack can be solved using both Greedy algorithm and Dynamic Programming but 0-1 Knapsack can not be solved using greedy Algorithm because of following two key ingredient leading to DP solution,
-  0-1 Knapsack contains Optimal Substructure, an optimal solution to the problem contains within optimal solution of Subproblems.
- Overlapping subproblems as  same subproblem will be visited again and again (subproblem share sub-subproblem)


when with each item i the multiplier is provided v[i] then the problem is same as fractional knapsack we can arrange the items according to value per unit weight*v[i] instead of only value per unit weight .
As it is a added on problem of fractional Knapsack ,so it can be solved using DP as well

**Comment by jstjyoti** [comment]
Should I write the explanation and add two files (fractional Knapsack and value multiplier fractional kapsack)
and explain all the way for using greedy method in codes as well?

**Comment by ramitsawhney27** [comment]
@jstjyoti yes please.
