### ISSUE TITLE
0-1 Knapsack Algorithm (Dynamic Programming)

### ISSUE THREAD

**Issue by shivhek25** [sahilbansal17/Competitive_Coding#134]
I would like to work on the 0-1 knapsack algorithm based on dynamic programming.

**Comment by ramitsawhney27** [comment]
Modify this by taking as input a positive integer k, such that while maximizing profit within the weight limit, you select at max k items.

**Comment by shivhek25** [comment]
Okay, I'll send in the algorithm soon.
