### ISSUE TITLE
Implementation Of Queue Data structure

### ISSUE THREAD

**Issue by Anujg935** [sahilbansal17/Competitive_Coding#147]
A queue is useful and a basic data structure. However, there are some different ways to implement it. I want' to implement queue following ways:-
Both the ways are a generic programmed(i.e not for any specific data type,  student will also learn about the practical use of template in this data structure)

- [x] Queue Using Dynamic Array(i.e implementing a queue using the array without any memory issue of filling the array)

- [x] Queue Using LinkedList
the above are the two programs that I want to code please assign it to me as soon as possible.

**Comment by jstjyoti** [comment]
I want to  work on Queue using Linked List

**Comment by Anujg935** [comment]
only the creator of the issue will be assigned the issue.
