### ISSUE TITLE
Minimum cost algorithm 

### ISSUE THREAD

**Issue by shivhek25** [sahilbansal17/Competitive_Coding#153]
I would like to work on a DP based approach to calculate the minimum cost in a 2D array when moving from (0,0) to destination such that we can only move down, right or diagonally (down-right).

**Comment by ramitsawhney27** [comment]
Modify this such that:
1. You can start anywhere.
2. Moves allowed are up, down, diagonal left and diagonal right.

**Comment by sahilbansal17** [comment]
@shivhek25 Please confirm whether you will be working on it.

**Comment by shivhek25** [comment]
Can't work on it right now, sorry.

**Comment by arnav-mandal1234** [comment]
You can work on the idea you suggested. @ramitsawhney27  I didn't get you. Why only up, down, diagonal left and diagonal right? 
We can add another issue where we can start anywhere and move in all the 8 directions. It is a medium-hard level issue. @sahilbansal17  look into this.
If you agree then make another issue.

**Comment by shivhek25** [comment]
Okay @arnav-mandal1234
