### ISSUE TITLE
Find subsets of an array with target sum

### ISSUE THREAD

**Issue by Aashu24** [sahilbansal17/Competitive_Coding#157]
Given an array of n numbers and a target sum, the problem is to print all the subsets of that array whose elements sum to the target sum. For eg.- For the array {1,2,3} and the target sum = 3, the subsets will be {1,2} and {3}.

I would like to work on this problem in Java.

**Comment by ramitsawhney27** [comment]
Instead of this, solve the subset sum problem (can google it), and instead of returning a boolean value in that, return 1 if possible, or the minimum difference possible if not possible.
