### ISSUE TITLE
Print Keypad Combinations Code (Recursive Problem)

### ISSUE THREAD

**Issue by Anujg935** [sahilbansal17/Competitive_Coding#167]
### **Print Keypad Combinations Code**
Given an integer n, using phone keypad find out and print all the possible strings that can be made using digits of input n.
**Note :** The order of strings are not important. Just print different strings in new lines.

**Input Format :**
`Integer n`
**Output Format :**
`All possible strings in different lines`
**Constraints :**
`1 <= n <= 10^6`
**Sample Input:**
`23`
**Sample Output:**
```
ad
ae
af
bd
be
bf
cd
ce
cf
```
I want to code this problem please assign it to me if you find this problem intresting and useful

**Comment by sahilbansal17** [comment]
This is an easy problem that is available on some online platform, so can't be accepted.
