### ISSUE TITLE
Sprial Pattern

### ISSUE THREAD

**Issue by jstjyoti** [sahilbansal17/Competitive_Coding#171]
**Problem**
Print the following pattern: for any integer n(number of lines) input by the user 
for input n=5,
output
1    2    3     4    5
16  17  18  19   6
15  24  25  20   7
14  23  22  21   8
13  12  11  10   9

for input  n=3,
output:
1    2    3
8    9    4
7    6    5

Explanation: This is a spiral pattern asked in many competitive coding or coding interviews .
I want to implment this using C programming and explain my logic to simplify and solve this pattern.

**Comment by jstjyoti** [comment]
Solved in PR #170

**Comment by sahilbansal17** [comment]
@jstjyoti You should wait for confirmation from mentors for issues related to some specific problem solutions (not direct DS/Algo implementations) since they might not be awarded points. Be careful from next time.
