### ISSUE TITLE
Hills and Valleys(Codechef)

### ISSUE THREAD

**Issue by jstjyoti** [sahilbansal17/Competitive_Coding#172]
**Problem:**
Chef has N numbers from 1 to N. He calls an array of integers special if the elements initially increase then decrease or the other way i.e. initially decrease then increase. He is fasinated by such arrays as he feels that they represent hills and valleys! Given the numbers that the chef has find the number of special arrays he can form using all the numbers 1 to N.
**Input**
First line contains T- number of test cases.
Each of the next T lines contains the value of N for each testcase.
**Output**
For each test case output in seperate lines the number of special arrays that can be formed modulo 1000000007 (109+7).
**Constraints**
1<= T <= 103 
1<= N <= 109

_Example
Input:
3
2
3
100
Output:
0
4
976371281_
 **Explanation**
**For N=3 the special arrays are:
[1, 3, 2]
[2, 3, 1]
[2, 1, 3]
[3, 1, 2]**

**Comment by ramitsawhney27** [comment]
Doesn’t make sense to directly do this. You could always submit it on codechef anyway. Not sure what you get to learn vis GSSoC through this.
