### ISSUE TITLE
Tree data structure

### ISSUE THREAD

**Issue by sourabh1031** [sahilbansal17/Competitive_Coding#184]
- [x] Traversal in a binary tree 
- [x]  Insertion and deletion in a binary tree
- [x]  Continuous and foldable binary trees
- [x] All the operations including finding height of the tree, etc.

**Comment by ramitsawhney27** [comment]
Go ahead.

**Comment by sahilbansal17** [comment]
@sourabh1031 Only the **Euler tour of the tree**, rest have been done.

**Comment by ramitsawhney27** [comment]
@sourabh1031 Demonstrate morris traversal as well.
