### ISSUE TITLE
HashMap

### ISSUE THREAD

**Issue by jstjyoti** [sahilbansal17/Competitive_Coding#189]
implementation of hash map using linear probing and searching element using keys in O(1).

1. -inserting an element into hasmap with their keys.
2. -deleting an element from hasmap.
3. -searching an element using key

I want to solve this issue for Hashmap Data Structure.

**Comment by sahilbansal17** [comment]
Also use chaining separately and provide the time complexity analysis for both **linear probing** and **chaining**.

**Comment by jstjyoti** [comment]
I will add two different code files separately for Linear Probing and Chaining.

**Comment by sahilbansal17** [comment]
Okay fine.

**Comment by shivhek25** [comment]
@sahilbansal17 Can I work on cuckoo hashing ?

**Comment by sourabh1031** [comment]
@jstjyoti  can i work on this issue if you don't want

**Comment by jstjyoti** [comment]
OK fine you can
