### ISSUE TITLE
Number to name

### ISSUE THREAD

**Issue by tanvi15** [sahilbansal17/Competitive_Coding#199]
Given a non-negative number, print the english words for it
For eg : 123
One hundred twenty three

**Comment by ramitsawhney27** [comment]
@tanvi15 we’ve seen you solve good tough problems. I don’t see any point in opening issues for such trivial problems considering you can do much better.

**Comment by tanvi15** [comment]
@ramitsawhney27 uhm okay, I don't know where to search for better questions :/
