### ISSUE TITLE
Range Query

### ISSUE THREAD

**Issue by Aashu24** [sahilbansal17/Competitive_Coding#219]
Given Q queries, with each query consisting of two integers L and R, the task is to find the total numbers between L and R (Both inclusive), having atmost three set bits in their binary representation.
The values of L and R lie within the range [0, 10^18] (both inclusive).
Example:
Input : Q = 2
        L = 3, R = 7
        L = 10, R = 16
Output : 5
              6
For the first query, valid numbers are 3, 4, 5, 6, and 7.
For the second query, valid numbers are 10, 11, 12, 13, 14 and 16.

I will like to work on this problem. Please assign it to me.

**Comment by mohitj27** [comment]
can you provide some test cases
