### ISSUE TITLE
Number permutation

### ISSUE THREAD

**Issue by tanvi15** [sahilbansal17/Competitive_Coding#228]
Given an integer n, find a permutation of numbers from 1 to n such that the sum of two consecutive numbers of that permutation is a perfect square. 

Eg : Input : 17
Output : 16, 9, 7, 2, 14, 11, 5, 4, 12, 13, 3, 6, 10, 15, 1, 8, 17
Explanation : 16+9 = 25 = 5 * 5, 9+7 = 16 = 4 * 4, 7+2 = 9 = 3 * 3 and so on.

Modifications welcome.

**Comment by ramitsawhney27** [comment]
Go ahead
