### ISSUE TITLE
Minimum product of indices for common elements 

### ISSUE THREAD

**Issue by shivhek25** [sahilbansal17/Competitive_Coding#234]
I would like to work on an algorithm that finds the minimum product of indices for common elements in 2 different arrays (STL based greedy approach).

**Comment by sahilbansal17** [comment]
@shivhek25 Could you please elaborate giving a few examples?

**Comment by shivhek25** [comment]
Say, the arrays are 
a : 3 1 2
b : 1 2 1
(1-based indexing)

The possible common elements are (a2,b1), (a2,b3), (a3,b2)
Product of indices in each case : 2, 6, 6
Output : 2

**Comment by sahilbansal17** [comment]
It is very easy.

**Comment by shivhek25** [comment]
Yes, but I was hoping to do it in reduced complexity using the knowledge of vectors and pairs.

**Comment by sahilbansal17** [comment]
You would simply store the pair of elements and indices and sort them. Isn't it?

**Comment by shivhek25** [comment]
Yes, and then check for corresponding elements by maintaining indices of both arrays. O(m+n) complexity basically instead of O(mn).

**Comment by sahilbansal17** [comment]
Still, sorting would take `O(n logn)`, so how is it `O(m + n)` ?

**Comment by shivhek25** [comment]
Overlooked the change in complexity due to the sorting part.
It's still better than O(mn) though.

**Comment by sahilbansal17** [comment]
But, its so easy to implement. Sorry, I am closing this issue, you have the potential to take up more advanced algorithms.
