### ISSUE TITLE
Implementation Of Generic Tree with custom functions

### ISSUE THREAD

**Issue by Anujg935** [sahilbansal17/Competitive_Coding#244]
Generic trees are the starting point of learning a Tree data structure i want to implement Generic tree data structures with following custom made function which helps the beginner student to learn the tree data structure with ease:-
- [x] **Level Wise Take Input Function**
- [x] **Level Wise Print Output Function**
- [x] **Counting Number Of Nodes Function**
- [x] **Sum Of Data Of all Nodes Function**
- [x] **Maximum Data Node Function**
- [x] **Count Leaf Node Function**
- [x] **Find Height of Tree Function**
- [x] **Print at Depth/Level Function**
- [x] **Pre Order Traversal**
- [x] **Post Order Traversal**

I think after learning all the above methods /function .It becomes very beneficial to get everything at single place.Student will gain more than enough knowledge to learn about different specific trees.Please assign it to me as i think it isn't implemented earlier.

**Comment by Anujg935** [comment]
please have a look at the issue it has been more than 3 days i have raised the issue.

**Comment by vikasgola** [comment]
@Anujg935  which language are you going to use?

**Comment by Anujg935** [comment]
C++

**Comment by vikasgola** [comment]
@Anujg935 go ahead.
