### ISSUE TITLE
String matching algorithms

### ISSUE THREAD

**Issue by h-sinha** [sahilbansal17/Competitive_Coding#247]
Given a text and a pattern, find all occurrences of the pattern in the text.
- [x] Naive approach

- [x] Rabin-Karp Algorithm

- [x] KMP Algorithm

**Comment by shivhek25** [comment]
Can I work on the KMP algorithm ?

**Comment by h-sinha** [comment]
I have started working on it. You can take up Rabin-Karp if you want

**Comment by shivhek25** [comment]
Okay, I can take up Rabin-Karp then.

**Comment by pritamnegi** [comment]
Can I work on Naive Approach??

**Comment by h-sinha** [comment]
Sure.Go ahead @pritamnegi

**Comment by vikasgola** [comment]
**Difficulty Level:-**
Naive Approach:  Intermediate
KMP:  Pro
RKA:.  Pro

**Comment by h-sinha** [comment]
@shivhek25 are you working on RKA?

**Comment by sahilbansal17** [comment]
@h-sinha You can start working.
