### ISSUE TITLE
Matrix rotation 

### ISSUE THREAD

**Issue by shivhek25** [sahilbansal17/Competitive_Coding#262]
I wish to work on matrix rotation.

**Comment by ramitsawhney27** [comment]
Open and work on new issues once you’re done with your older one (min cost in a matrix all 8 dimensions)

**Comment by shivhek25** [comment]
@ramitsawhney27 I am not sure if that issue was assigned to me. @arnav-mandal1234 asked @sahilbansal17 to consider the issue and open a new one if needed.

**Comment by ramitsawhney27** [comment]
I’ll reopen it and assign it to you.

**Comment by arnav-mandal1234** [comment]
Actually, you can open the issue but if he wants to take this issue he can why closing the issue?
@shivhek25 I am reopening this issue and if you want to take this, then I will assign it to you.

**Comment by shivhek25** [comment]
Okay @arnav-mandal1234

**Comment by arnav-mandal1234** [comment]
@shivhek25 do you want to work on this? Then i will assign you.
