### ISSUE TITLE
STL Implementation

### ISSUE THREAD

**Issue by sourabh1031** [sahilbansal17/Competitive_Coding#263]
- [x] Vector
- [x] List
- [x] Pair
- [x] Heap

**Comment by arnav-mandal1234** [comment]
Hope you submit PR within two days.

**Comment by shivhek25** [comment]
Is @sourabh1031 working on all of these ?

**Comment by sourabh1031** [comment]
@shivhek25 currently i am working on all but if i am not able to do so after two days you can request for it

**Comment by sourabh1031** [comment]
@shivhek25 you can work on the last one

**Comment by sourabh1031** [comment]
@imkaka okay

**Comment by imkaka** [comment]
okey thanks.
