### ISSUE TITLE
Kth smallest element in an array

### ISSUE THREAD

**Issue by lavishsaluja** [sahilbansal17/Competitive_Coding#267]

**Comment by pritamnegi** [comment]
Can i work on this issue???

**Comment by lavishsaluja** [comment]
Working on this already.

**Comment by pritamnegi** [comment]
Ok fine

**Comment by imkaka** [comment]
@sahilbansal17 I want to work on this Please Assign it.

**Comment by sahilbansal17** [comment]
@imkaka You can start working, the program should have a complexity of `O(N)`.
