### ISSUE TITLE
Array implementations

### ISSUE THREAD

**Issue by sahilbansal17** [sahilbansal17/Competitive_Coding#28]
- [x] Insertion, Deletion, Search (Linear, Binary) 
- [x] Array doubling and its amortized complexity 
- [x] Dynamic Arrays: Vector (STL) 
Refer to [Data structures wiki page](https://github.com/sahilbansal17/Competitive_Coding/wiki/Data-Structures).

**Comment by Eunoia1729** [comment]
I want to work on this

**Comment by aayushinigam** [comment]
Can I take up this issue?

**Comment by sourabh1031** [comment]
I want like to work on this issue

**Comment by sourabh1031** [comment]
i would love to work on the issue

**Comment by sarnava1** [comment]
I would like to work on this.

**Comment by frost-queen** [comment]
i would like to work on this issue

**Comment by aryan-harsh** [comment]
I would like to work on this

**Comment by shiv07tiwari** [comment]
I would like to work on this issue !

**Comment by sahilbansal17** [comment]
@Eunoia1729 @sourabh1031 @sarnava1 @shiv07tiwari 
Please select one of the three tasks.

**Comment by shiv07tiwari** [comment]
@sahilbansal17 I would like to work on the first task.

**Comment by sahilbansal17** [comment]
Yes, you can start working but then until this is complete, you can't take up any other issues, right?

**Comment by shiv07tiwari** [comment]
Ya sure, so I am working on the first task, thanks !

**Comment by sarnava1** [comment]
@sahilbansal17  I would like to work on the second task.

**Comment by sarnava1** [comment]
@sahilbansal17 can I write the discussions on the amortized time complexity in comments within the code itself?

**Comment by Eunoia1729** [comment]
@sahilbansal17 I can work on the first task.

**Comment by sahilbansal17** [comment]
@sarnava1 Yes sure. 
@Eunoia1729 Fine.

**Comment by sourabh1031** [comment]
@sahilbansal17 Please assign first task to me

**Comment by sahilbansal17** [comment]
@sourabh1031 This issue is now claimed by others. Please pick some different issue or create another issue referring to the list in the Wiki for DS/Algos.

**Comment by shivhek25** [comment]
@sahilbansal17 I would like to work on the first sub-task.

**Comment by shivhek25** [comment]
@sahilbansal17 What exactly do we need to work on in the second sub-task ? Algorithm to show the amortisation process ?

**Comment by shivhek25** [comment]
Okay, I can work on this.
