### ISSUE TITLE
List implementations

### ISSUE THREAD

**Issue by sahilbansal17** [sahilbansal17/Competitive_Coding#29]
- [x] Insertion, Deletion, Search, Reversal, Traversal 
- [x] Doubly and circular linked list [working: @moulikcipherX ]
- [x] List implementations in STL(List, Forward List)

Refer to [Data structures wiki page](https://github.com/sahilbansal17/Competitive_Coding/wiki/Data-Structures).

**Comment by Eunoia1729** [comment]
I want to  contribute to this

**Comment by aayushinigam** [comment]
Can I take up this issue?

**Comment by aditya81070** [comment]
@aayushinigam surely you can take this issue

**Comment by aryan-harsh** [comment]
I want to contribute to this. Can i take u this issue?

**Comment by frost-queen** [comment]
@aayushinigam  @aryan-harsh  can we divide up the work? there are three components we can take one each?

**Comment by aryan-harsh** [comment]
@frost-queen sure.

**Comment by frost-queen** [comment]
okay let's wait up for @aayushinigam , btw i would like to work upon the list implementations in STL

**Comment by aayushinigam** [comment]
@frost-queen @aryan-harsh I don't mind.But let's first have a mentor's approval for this.Then we'll do this way.

**Comment by sahilbansal17** [comment]
Each of you can take one of the three tasks.

**Comment by aryan-harsh** [comment]
i wish to take the first one,  Insertion, Deletion, Search, Reversal, Traversal          
 @aayushinigam  you may take the second , Doubly and circular linked list
@frost-queen take the list implementation. (STL) .    Is that fine?

**Comment by aayushinigam** [comment]
@aryan-harsh I would like work on doubly and circular linked lists. @frost-queen has already mentioned her preference. Are you okay with this?

**Comment by aryan-harsh** [comment]
Sure, I am comfortable.  @aayushinigam  @frost-queen

**Comment by frost-queen** [comment]
yeah that sounds good :+1:

**Comment by sahilbansal17** [comment]
OK fine. Now all three of you cannot claim any other issue until this is completed and merged. Please refer to the [GSSoC Wiki Page](https://github.com/sahilbansal17/Competitive_Coding/wiki/GSSoC) if you haven't already.

**Comment by dhairyabaweja** [comment]
Can I contribute to one of the subtasks of the issue?

**Comment by rishabhgarg25699** [comment]
I implemented 2 files on linked list .But you do not add on it.Please add on it

**Comment by aayushinigam** [comment]
Second task is up for grabs. I'm not working on it.

**Comment by moulikcipherX** [comment]
Can you please assign the second task.

**Comment by sahilbansal17** [comment]
@moulikcipherX Go ahead.

**Comment by moulikcipherX** [comment]
Okay thanx

**Comment by ashubly25** [comment]
May i work on second task?

**Comment by sahilbansal17** [comment]
@ashubly25 It is taken up by @moulikcipherX. You can take up another issues.

**Comment by ashubly25** [comment]
sure. :)

**Comment by sahilbansal17** [comment]
@moulikcipherX It has been two days, If you don't send a PR by tomorrow, it will be assigned to @ashubly25.

**Comment by moulikcipherX** [comment]
Sorry for Late submission.
Can you tell me which functions we have to implement?
@sahilbansal17
