### ISSUE TITLE
Add Graph algorithms

### ISSUE THREAD

**Issue by sahilbansal17** [sahilbansal17/Competitive_Coding#3]
Implement the following **Elementary Graph Algorithms** taking reference from the Chapter 22 of the book **Introduction to Algorithms**
- [x] Breadth-first search 
- [x] Depth-first search
- [x] Topological sort

**Comment by ashish4321** [comment]
I can add the code

**Comment by agarwalprashasti** [comment]
I want to contribute to this

**Comment by Eunoia1729** [comment]
I would like to contribute to this

**Comment by syedjahangirpeeran** [comment]
I would like to code it!

**Comment by bscoolcoder** [comment]
I would like to contribute to it

**Comment by h-sinha** [comment]
I would like to contribute to this

**Comment by sarnava1** [comment]
I would like to work on this.

**Comment by aryan-harsh** [comment]
i would like to work on this

**Comment by aryan-harsh** [comment]
i would like to work on this

**Comment by shiv07tiwari** [comment]
I would like to work on this project contributing to first and second tasks !

**Comment by sahilbansal17** [comment]
@shiv07tiwari Please go through the guidelines to contribute in [GSSoC wiki page](https://github.com/sahilbansal17/Competitive_Coding/wiki/GSSoC). You are allowed to take up only one issue at a time.

**Comment by shiv07tiwari** [comment]
@sahilbansal17 Okay. So can I start contributing on the last issue I commented on ?

**Comment by sahilbansal17** [comment]
Yes.

**Comment by sourabh1031** [comment]
@sahilbansal17 Can i work on this issue implementing first and second task

**Comment by sahilbansal17** [comment]
@sourabh1031 This issue has already been implemented.

**Comment by jstjyoti** [comment]
I want to contribute to first two.

**Comment by sahilbansal17** [comment]
@jstjyoti This is already done. Please find yourself another topic to work on, create an issue if it already doesn't exit and start working. Read [GSSoC Wiki Page](https://github.com/sahilbansal17/Competitive_Coding/wiki/GSSoC) thoroughly for Guidelines on contribution.

**Comment by jstjyoti** [comment]
Sir,
I am working on & #48 sorting algorithm. Is it okay?

**Comment by sahilbansal17** [comment]
@jstjyoti Yes.

**Comment by imkaka** [comment]
@sahilbansal17 I want to work on this! Please assign it.

**Comment by sahilbansal17** [comment]
@imkaka I think you have missed the conversations above. Please read them.
