### ISSUE TITLE
MaxPriority Queue Implementation

### ISSUE THREAD

**Issue by Anujg935** [sahilbansal17/Competitive_Coding#305]
i want to implement Max-Priority Queue .It's available in STL but i always feel so the person should know how to build what the person is using.So i want to build the min priority queue with the following functionalities:
- [x] **getMin**
- [x] **insert**
- [x] **removeMin**
- [x] **getSize**
- [x] **isEmpty**

**Comment by sahilbansal17** [comment]
Just small changes need to be made in the Min-priority queue, you won't be getting extra points for it.

**Comment by Anujg935** [comment]
okay,still i will do it.just a question will i have to do the commenting of the maxPriorityQueue or can be just say in comments that please see minPriorityQueue  program for concept.

**Comment by sahilbansal17** [comment]
Yes, add comments also, just small changes need to be done, I think.

**Comment by Anujg935** [comment]
okay
