### ISSUE TITLE
Path Sum Root to Leaf

### ISSUE THREAD

**Issue by Anujg935** [sahilbansal17/Competitive_Coding#311]
Given a binary tree and a number k, print out all root to leaf paths where the sum of all nodes value is same as the given number k.This is a very famous as well as important problem on binary tree .so i want to work on this.

**Comment by Aashu24** [comment]
@Anujg935 This has already been added. Check Algorithms->Trees->Binary tree->RootToLeaf. Issue #246 and PR #249 .

**Comment by sahilbansal17** [comment]
No, @Anujg935 Kindly don't work on this since it is already done.
