### ISSUE TITLE
Minimum Spanning Tree

### ISSUE THREAD

**Issue by sahilbansal17** [sahilbansal17/Competitive_Coding#34]
Implement Minimum Spanning Tree algorithms:
- [x] Kruskal's algorithm [working: @Dhiraj240 ]
- [x] Prim's algorithm (Adjacency Matrix Implementation) [done: @tanvi15 ]
- [x] Prim's algorithm (Adjacency List Implementation) 

Refer to [Algorithms](https://github.com/sahilbansal17/Competitive_Coding/wiki/Algorithms) wiki page.

**Comment by Dhiraj240** [comment]
Can  i work on this issue?

**Comment by tanvi15** [comment]
I wish to work on this issue.
@Dhiraj240 you take one, I'll take the other?

**Comment by Dhiraj240** [comment]
Okay fine @tanvi15

**Comment by sahilbansal17** [comment]
Yes, its fine, one of you can implement *Kruskal's algorithm* and the other person can work on *Prim's algorithm*.

**Comment by tanvi15** [comment]
Now working on adjacency list implementation for Prim's algorithm

**Comment by sahilbansal17** [comment]
@tanvi15 Please confirm whether you are working on the adjacency list implementation!

**Comment by tanvi15** [comment]
@sahilbansal17 yes, I was waiting for approval on the matrix implementation.
