### ISSUE TITLE
Min Cost Path

### ISSUE THREAD

**Issue by Anujg935** [sahilbansal17/Competitive_Coding#342]
Given an integer matrix of size m*n, you need to find out the value of minimum cost to reach from the cell (0, 0) to (m-1, n-1).
From a cell (i, j), you can move in three directions : (i+1, j), (i, j+1) and (i+1, j+1).
Cost of a path is defined as the sum of values of each cell through which path passes.
This is a well known DP problem.But it's not easy for beginners to directly implement DP approach so it's good way to first solve them with brute force,than with memoization and after that comes the time of DP.
- [ ] **Brute Force Approach**  (Time complexity **O(n^2)**)
- [ ] **Memoization Technique**  (Time complexity **O(n)**)
- [ ] **Dynamic Programming**  (Time complexity **O(n)**)

**This is a advance problem** .In this students will learn about applying DP on 2d array.

**Comment by Aashu24** [comment]
@sahilbansal17 A similar issue was submitted by someone a long time back. Issue #153 .
