### ISSUE TITLE
minimum steps required to make one string equal to other

### ISSUE THREAD

**Issue by Anujg935** [sahilbansal17/Competitive_Coding#349]
Given two strings s and t of lengths m and n respectively, find the Edit Distance between the strings. Edit Distance of two strings is minimum number of steps required to make one string equal to other. In order to do so you can perform following three operations only :
1. Delete a character
2. Replace a character with another one
3. Insert a character
I am going to implement it using following 3 approaches:-
- [ ] **Brute Force Approach**  
- [ ] **Memoization Technique**  
- [ ] **Dynamic Programming**

**Comment by Aashu24** [comment]
@sahilbansal17 Issue #132 and PR #152 . I submitted the exact same issue and the problem was modified by you.
