### ISSUE TITLE
Add instructions for Hacktoberfest

### ISSUE THREAD

**Issue by sahilbansal17** [sahilbansal17/Competitive_Coding#368]
Update the readme so that hacktoberfest participants can contribute to this repository and get started with open source.

**Comment by akarshsingh9** [comment]
may i take this one?

**Comment by sahilbansal17** [comment]
@akarshsingh9  Sure. Just add a new section about **How to contribute to Hacktoberfest ?**

 It should be brief and up to the point. Add relevant links.

**Comment by akarshsingh9** [comment]
Please review PR #373 and let me know of any changes required

**Comment by sahilbansal17** [comment]
Good work @akarshsingh9 @crouther .
