### ISSUE TITLE
Dijkstra's Algorithm

### ISSUE THREAD

**Issue by Sandip75** [sahilbansal17/Competitive_Coding#37]
I want to work on Dijkstra algorithm.

**Comment by Aashu24** [comment]
Can I work on this or has it already been assigned to someone else?

**Comment by sahilbansal17** [comment]
@Aashu24 Yes, you can work on it.

**Comment by sahilbansal17** [comment]
Yes, sure, @frost-queen you can start working on it.

**Comment by Aashu24** [comment]
@sahilbansal17 You told me to start working on this issue today and now you told @frost-queen to work on this issue. Can two people work on the same issue?

**Comment by sahilbansal17** [comment]
Okay then @Aashu24 you work on it. @frost-queen Please take another issue since @Aashu24 already claimed earlier.

**Comment by Aashu24** [comment]
@sahilbansal17 Alright!

**Comment by Aashu24** [comment]
@sahilbansal17 I am done with the code. I'll write the explanations and create a pull request by today evening.
