### ISSUE TITLE
Add computational geometry algorithms

### ISSUE THREAD

**Issue by sahilbansal17** [sahilbansal17/Competitive_Coding#370]
- [ ] Graham Scan algorithm for Convex Hull in **O(nlogn)**
- [ ] Online construction of 3-D convex hull in **O(n<sup>2</sup>)**
- [ ] Bentley Ottmann algorithm to list all intersection points of n line segments in **O((n+I)logn)**
- [ ] Rotating Calipers technique
- Line sweep/Plane sweep algorithms - 
    - [ ] Area/perimeter of union of rectangles
    - [ ] Closest pair of points
- [ ] Area of union of circles
- [ ] Delayunay triangulation of n points in **O(nlogn)**
- [ ] Voronoi diagrams of n points in **O(nlogn)** using Fortunes algorithm
- Point in a polygon problem
    - [ ] **O(n)** solution without preprocessing
    - [ ] **O(logn)** algorithm with **O(nlogn)** preprocessing for convex polygons
- Problem solutions for following problems on SPOJ:
    - [ ] [BSHEEP](https://www.spoj.com/problems/BSHEEP/)
    - [ ] [BULK](https://www.spoj.com/problems/BULK/)
    - [ ] [SEGVIS](https://www.spoj.com/problems/SEGVIS/)
    - [ ] [CONDUIT](https://www.spoj.com/problems/CONDUIT/)
    - [ ] [RUNAWAY](https://www.spoj.com/problems/RUNAWAY/)
    - [ ] [DIRVS](https://www.spoj.com/problems/DIRVS/)
    - [ ] [SHAMAN](https://www.spoj.com/problems/SHAMAN)
    - [ ] [TCUTTER](https://www.spoj.com/problems/TCUTTER)
    - [ ] [LITEPIPE](https://www.spoj.com/problems/LITEPIPE)
    - [ ] [RHOMBS](https://www.spoj.com/problems/RHOMBS)
    - [ ] [FSHEEP](https://www.spoj.com/problems/FSHEEP)
    - [ ] [FLBRKLIN](https://www.spoj.com/problems/FLBRKLIN)
    - [ ] [CERC07P](https://www.spoj.com/problems/CERC07P)

**Comment by MananJethwani** [comment]
can i submit solution for Graham Scan algorithm for Convex Hull in c++

**Comment by sahilbansal17** [comment]
@MananJethwani Sure.
