### ISSUE TITLE
Add flow network / matching algorithms

### ISSUE THREAD

**Issue by sahilbansal17** [sahilbansal17/Competitive_Coding#375]
- [ ] Maximum flow using Ford Fulkerson method
    - Solutions to following SPOJ problems:
        - [ ] [TAXI](https://www.spoj.com/problems/TAXI/)
        - [ ] [POTHOLE](https://www.spoj.com/problems/POTHOLE)
        - [ ] [IM](https://www.spoj.com/problems/IM)
        - [ ] [QUEST4](https://www.spoj.com/problems/QUEST4)
        - [ ] [MUDDY](https://www.spoj.com/problems/MUDDY)
        - [ ] [EN](https://www.spoj.com/problems/EN)
        - [ ] [CABLETV](https://www.spoj.com/problems/CABLETV)
        - [ ] [STEAD](https://www.spoj.com/problems/STEAD)
        - [ ] [NETADMIN](https://www.spoj.com/problems/NETADMIN)
        - [ ] [COCONUTS](https://www.spoj.com/problems/COCONUTS)
        - [ ] [OPTM](https://www.spoj.com/problems/OPTM)
- [ ] Maximum flow using Dinics algorithm
    - [ ] Problem [PROFIT](https://www.spoj.com/problems/PROFIT) on SPOJ
- Minimum Cost maximum flow
    - [ ] Successive shortest path algorithm
    - [ ] Cycle cancelling algorithm
- [ ] Maximum weighted bipartite matching (Kuhn Munkras algorithm / Hungarian method)
    - Solutions to following SPOJ problems:
        - [ ] [GREED](https://www.spoj.com/problems/GREED)
        - [ ] [SCITIES](https://www.spoj.com/problems/SCITIES)
        - [ ] [TOURS](https://www.spoj.com/problems/TOURS)
- [ ] Stoer Wagner min-cut algorithm
- [ ] Hopcroft Karp bipartite matching algorithm
    - [ ] Problem [ANGELS](https://www.spoj.com/problems/ANGELS) on SPOJ
- [ ] Maximum matching in general graph (blossom shrinking)
- [ ] Gomory-Hu trees 
    - [ ] Problem [MCQUERY](https://www.spoj.com/problems/MCQUERY) on SPOJ
- [ ] Chinese Postman problem

**Comment by Naba7** [comment]
Can I be assigned to this issue? @sahilbansal17

**Comment by sahilbansal17** [comment]
Yes sure. @Naba7

**Comment by sahilbansal17** [comment]
Since there are multiple sub tasks, please choose one at a time.

**Comment by TheAlakazam** [comment]
I want to work on this issue too.

**Comment by sahilbansal17** [comment]
@TheAlakazam Sure, take up a few subtasks at a time!

**Comment by namanvats** [comment]
Can I take up this issue?
