### ISSUE TITLE
Strassen's Algorithm (Divide and Conquer)

### ISSUE THREAD

**Issue by syedjahangirpeeran** [sahilbansal17/Competitive_Coding#38]
- [ ] Strassen's Algorithm for Matrix multiplication

**Comment by sahilbansal17** [comment]
@syedjahangirpeeran Please update the issue heading and description properly.

**Comment by syedjahangirpeeran** [comment]
I would like to work on above algorithms.

**Comment by sahilbansal17** [comment]
@syedjahangirpeeran This is not a good way. All these algorithms are from different categories. I suggest you to create one issue at a time for a single algorithm.

**Comment by sahilbansal17** [comment]
@syedjahangirpeeran You can only take up one algorithm at a time. I have updated this issue accordingly. Is it fine?

**Comment by syedjahangirpeeran** [comment]
Yes, Sure.

**Comment by sahilbansal17** [comment]
This issue can be claimed.
