### ISSUE TITLE
Add solutions  from URI online judge

### ISSUE THREAD

**Issue by AnneLivia** [sahilbansal17/Competitive_Coding#386]
I want to add some solutions to problems from URI Online Judge (https://www.urionlinejudge.com.br)

**Comment by sahilbansal17** [comment]
@AnneLivia Sure. Go ahead.
Follow these git guidelines.
1. First fetch the changes from the original repository's master branch. 
**Keep your fork's main development branch updated with upstream's**. Use the following commands:
`git remote add upstream https://github.com/sahilbansal17/Competitive_Coding`
`git checkout master`
`git pull upstream master`
`git push origin master`
2. Work on Pull request in a new branch (good git practices):
`git checkout -b TOPIC-BRANCH`
`git add FILES`
`git commit`
`git push origin TOPIC-BRANCH`
3. Go to your fork on GitHub, switch to the topic branch, and click *Compare & pull request*.

[Reference](https://github.com/susam/gitpr/blob/master/README.md)
