### ISSUE TITLE
Check which algos and DS have been implemented and remove from being implemented list

### ISSUE THREAD

**Issue by Naba7** [sahilbansal17/Competitive_Coding#390]
Please assign me this issue @sahilbansal17

**Comment by Naba7** [comment]
Since,binary search algorithm has been implemented Can you delete it from algorithms to be implemeted

**Comment by sahilbansal17** [comment]
Actually, the list currently doesn't mention which algorithms are implemented... 
The lists are to be updated accordingly adding a tag whether something is done already.

**Comment by Naba7** [comment]
Alright. Can I take up the issue?

**Comment by sahilbansal17** [comment]
Yes sure. I recommend you to create a markdown post [here](https://github.com/sahilbansal17/Competitive_Coding/tree/gh-pages-source/_posts) creating a table of list of algorithms and whether they are implemented or not.

Also, you can directly modify the [wiki page](https://github.com/sahilbansal17/Competitive_Coding/wiki/Algorithms).
