### ISSUE TITLE
Coin_change problem in java 

### ISSUE THREAD

**Issue by megha070** [sahilbansal17/Competitive_Coding#393]
@sahilbansal17 I would like to work on this issue!

**Comment by sahilbansal17** [comment]
The [greedy algorithm](https://github.com/sahilbansal17/Competitive_Coding/wiki/Algorithms#greedy-algorithms) is already present.
Do you want to work on [Dynamic Programming problem](https://github.com/sahilbansal17/Competitive_Coding/wiki/Algorithms#dynamic-programming) for coin change?

**Comment by megha070** [comment]
Yes!
