### ISSUE TITLE
Sorting algorithms in java

### ISSUE THREAD

**Issue by Ananyajain721** [sahilbansal17/Competitive_Coding#395]
@sahilbansal17 I would like to work on this issue.

**Comment by sahilbansal17** [comment]
Sure @Ananyajain721 
- Make sure you create a new branch and send Pull request from that new branch.
- Add your codes in a new folder named Java in [Sorting directory](https://github.com/sahilbansal17/Competitive_Coding/tree/master/Algorithms/Sorting).
- Also, your code should be written completely by you and follow the [Coding Standards](https://github.com/sahilbansal17/Competitive_Coding/wiki/Coding-Standards).

**Comment by bharati-21** [comment]
@sahilbansal17  what about this issue? Has this been solved?

**Comment by sahilbansal17** [comment]
Not yet, you can send a PR if you wish.

**Comment by bharati-21** [comment]
@sahilbansal17  how many days do I get to complete and submit after I make a PR?

**Comment by sahilbansal17** [comment]
There is no rule for that as of now in this repository, you can take your time.

**Comment by bharati-21** [comment]
@sahilbansal17  okay! I'd like to work on this!

**Comment by Ananyajain721** [comment]
@bharati-21 I have already worked on Insertion, Bubble and selection sort. Please comment here on which sort you are working so that our works do not collide.

**Comment by bharati-21** [comment]
@Ananyajain721  Then I'll work on merge sort, quicksort, heapsort and if possible radix sort? cool with you?

**Comment by Ananyajain721** [comment]
yeah :)

**Comment by sahilbansal17** [comment]
• Bucket, Counting & Insertion Sort: #414 ✔️ 
• QuickSort: #413 ✅
