### ISSUE TITLE
Max difference between nearest left and right smaller elements

### ISSUE THREAD

**Issue by megha070** [sahilbansal17/Competitive_Coding#396]
I would like to work on this!

**Comment by sahilbansal17** [comment]
Sure @megha070 
- Make sure you create a new branch and do commits in that, finally send Pull request from that new branch. Read [GitHub flow](https://help.github.com/en/articles/github-flow).
- Add your codes in the folder [Stacks](https://github.com/sahilbansal17/Competitive_Coding/tree/master/Algorithms/Stacks).
- Also, your code should be written completely by you and follow the [Coding Standards](https://github.com/sahilbansal17/Competitive_Coding/wiki/Coding-Standards).
