### ISSUE TITLE
reverse and sorting of stack

### ISSUE THREAD

**Issue by megha070** [sahilbansal17/Competitive_Coding#402]
@sahilbansal17  I would like to work on this.

**Comment by sahilbansal17** [comment]
Can you create a single issue grouping all similar algorithms/data structures together? 😛 
Name the issue with the name of data structure/class of algorithms.
In the description, add [task list](https://help.github.com/en/articles/about-task-lists) for all the algorithms.

**Comment by megha070** [comment]
Sure, I wasn't knowing if we could do that!
