### ISSUE TITLE
Stacks in java

### ISSUE THREAD

**Issue by megha070** [sahilbansal17/Competitive_Coding#403]
- [x] Reverse and Sorting of a stack
- [x] Prefix, Postfix, Infix conversions

**Comment by megha070** [comment]
@sahilbansal17 I would like to take this up.

**Comment by sahilbansal17** [comment]
@megha070 Kindly add the list of problems in task list format in the description above.

**Comment by megha070** [comment]
Codes to be implemented.
[ ]  Reverse and Sorting of a stack
[ ]  Prefix, Postfix, Infix conversions

**Comment by megha070** [comment]
@sahilbansal17  I would like to take this up.

**Comment by bharati-21** [comment]
Has this issue been assigned? I would like to work on this.

**Comment by sahilbansal17** [comment]
@bharati-21 This has been done, you can create new issues, considering the guidelines mentioned in the [Intro to contributing wiki page](https://github.com/sahilbansal17/Competitive_Coding/wiki/Introduction-to-Contributing).
