### ISSUE TITLE
Implementation of trie data structure

### ISSUE THREAD

**Issue by sourabh1031** [sahilbansal17/Competitive_Coding#41]
Trie is one of the useful data structures. I would like to implement it.

**Comment by Eunoia1729** [comment]
I would like to implement

**Comment by sahilbansal17** [comment]
@Eunoia1729 Please follow the guidelines, @sourabh1031 is already working on it!

**Comment by sahilbansal17** [comment]
1. Yes, you can work on another issue.
2. We will close and merge the PR when 3 mentors approve it.
