### ISSUE TITLE
Algorithm checklist wiki page

### ISSUE THREAD

**Issue by Naba7** [sahilbansal17/Competitive_Coding#412]
I bymistakely deleted the algorithms page you had created. The checklisted page. Sorry. I will make one by tonight.

**Comment by sahilbansal17** [comment]
I guess there is going back, you need not do the hard work
Since this is github:
https://stackoverflow.com/questions/24797429/how-do-i-undo-deleting-a-github-wiki-page

**Comment by sahilbansal17** [comment]
I have restored the file, never ignore the power of Git and Github! 😄

**Comment by Naba7** [comment]
Yes, Thanks. Btw I couldnt clone the wiki page as it says I had no access.?

**Comment by sahilbansal17** [comment]
I guess only the repository owner has rights to clone it.
