### ISSUE TITLE
Stack implementation python

### ISSUE THREAD

**Issue by kurianbenoy** [sahilbansal17/Competitive_Coding#417]

**Comment by tanaytoshniwal** [comment]
I would like to work on this issue @sahilbansal17

**Comment by sahilbansal17** [comment]
@tanaytoshniwal Please check whether this is already implemented in this repository.

**Comment by tanaytoshniwal** [comment]
@sahilbansal17 There's an implementation in C++, but the issue mentioned it clearly to implement it using Python.

**Comment by sahilbansal17** [comment]
Ok @tanaytoshniwal I will review your PR and merge it. 😄
