### ISSUE TITLE
Stack based algorithms Python

### ISSUE THREAD

**Issue by dinithiW** [sahilbansal17/Competitive_Coding#424]
I would like to work on the stack based algorithms using Python(Balanced Parenthesis Problems, Prefix, Postfix, Infix conversions, Reverse and Sorting of a stack)

**Comment by sahilbansal17** [comment]
Sure @dinithiW .

**Comment by RahulRavishankar** [comment]
Hey! Even I'm interested in working on this.

**Comment by sahilbansal17** [comment]
@RahulRavishankar Sure, kindly take up those algorithms which are not there in the repository yet.
