### ISSUE TITLE
Counting Inversions, Closest Pair (C++, Python) & graph algorithms (Python) 

### ISSUE THREAD

**Issue by KruZZy** [sahilbansal17/Competitive_Coding#433]
I would like to work on the following:

- [x] counting inversions (c++ & python)
- [x] closest pair of points (c++ & python)
- [x] dfs (python)
- [x] bfs (python)
- [x] topological sorting (python)
- [x] binary indexed trees (c++ & python)

**Comment by sahilbansal17** [comment]
@KruZZy Sure 👍

**Comment by aayusharma10** [comment]
I would like to work in Counting Inversions in C++ .

**Comment by anirudnits** [comment]
I can add Counting Inversion pairs in Python and also add Miller Rabin in python(as I saw that was missing).

**Comment by sahilbansal17** [comment]
@KruZZy Can you confirm if you are still working on Counting Inversions? Otherwise, @aayusharma10 and @anirudnits can contribute to that.

**Comment by KruZZy** [comment]
I have no problem with them contributing to that. I haven't got the chance to start working on it. 

@sahilbansal17 @anirudnits @aayusharma10

**Comment by anirudnits** [comment]
submitted the PR for _miller_rabin.py_ and _inversion_count.py_. Do have a look and let me know if there are any changes to be made. Thanks

**Comment by aayusharma10** [comment]
Submitted the PR for Inversion_count.cpp. Please have a look at it and let me know if any changes required. Thanks

**Comment by KruZZy** [comment]
All the problems on this issue has been solved. Congrats! I will close the issue now.

@sahilbansal17 @anirudnits @aayusharma10
