### ISSUE TITLE
Basic Stack implementation in python.

### ISSUE THREAD

**Issue by Sachindrck** [sahilbansal17/Competitive_Coding#439]
New to open source.

**Comment by Sachindrck** [comment]
I would like to work on simple stack problems like parenthesis balancing ,decimal to binary , infix to postfix , reversing a stack using recursion and many others.

**Comment by 20harshita** [comment]
New to open source . can i also contribute in this problem ?

**Comment by sahilbansal17** [comment]
@20harshita Sure, but make sure the code for same problem is not already there in the repository.
