### ISSUE TITLE
Organize files into well defined folders

### ISSUE THREAD

**Issue by sahilbansal17** [sahilbansal17/Competitive_Coding#440]
To make various contest solutions accessible, restructure the content in the **Problem Solutions** directory.

For example, in **fbHackerCup** folder, make subdirectories for contests held in different years.
Come up with such innovative methods to structure the content in a better way.

**Comment by theadityasam** [comment]
Hey sahil!
Would like to work on this issue.

**Comment by sahilbansal17** [comment]
Sure @theadityasam 
Use only `git mv` commands to do this.

**Comment by theadityasam** [comment]
Cool
