### ISSUE TITLE
Matrix Data Structure in cpp

### ISSUE THREAD

**Issue by captainnemo89** [sahilbansal17/Competitive_Coding#441]
checklist:
- [ ] determinant
- [ ] addition
- [ ] subtraction
- [ ] scalar multiplication
- [ ] multiplication
- [ ] transpose
- [ ] identity
- [ ] adjoint
- [ ] inverse

will add more.

**Comment by captainnemo89** [comment]
can I just have one file that runs others files' code for example ( driver code )?
and put different functions in different files.

**Comment by sahilbansal17** [comment]
It's better to create just one file with implementation of all functions since they will be quite small.

**Comment by DebadityaPal** [comment]
I would like to contribute to this repo

**Comment by TheAlakazam** [comment]
Hey, I wanna contribute to this, so should I add a Matrix folder to the Data Structure folder?

**Comment by sahilbansal17** [comment]
@captainnemo89 Please confirm if you are still working on it.
@TheAlakazam It has been assigned to @captainnemo89 so let's wait for his response.

**Comment by pratyanshupandey** [comment]
Can I work on this issue?

**Comment by captainnemo89** [comment]
sorry, will not be able to work on it.

**Comment by TheAlakazam** [comment]
@sahilbansal17 Can I work on this now?

**Comment by sahilbansal17** [comment]
Sure @TheAlakazam
