### ISSUE TITLE
Implementing Few Bit Masking Algorithms

### ISSUE THREAD

**Issue by NavonilDas** [sahilbansal17/Competitive_Coding#451]
- [x] Flip Bits 
- [x] Power of 2
- [x] Maximum XOR in a range
- [x] Finding a Unique number which is not repeated twice else every element is repeated twice
- [x] Count Number of Ways in which the Xor of two numbers is equal to the sum of these number.
  ## Problems 
- [Flipping Bits](https://www.hackerrank.com/challenges/flipping-bits/problem)
- [Sum Vs Xor](https://www.hackerrank.com/challenges/sum-vs-xor/problem)
- [Lonely Integer](https://www.hackerrank.com/challenges/lonely-integer/problem)
- [Maximizing Xor](https://www.hackerrank.com/challenges/maximizing-xor/problem)

**Comment by sahilbansal17** [comment]
@NavonilDas Looks great. You can get started with it!

**Comment by tanaytoshniwal** [comment]
I would like to implement the following bit masking algorithms:
- Check ith Bit
- Check Odd or Even
- Clear all bits from MSB
- Convert Number to Binary
- Flip ith bit
- Return First set bit
- Turn off First set bit
- Turn off ith bit
- Turn on ith bit

**Comment by sahilbansal17** [comment]
@tanaytoshniwal All these are one liner implementations, maybe create a single program with all these operations.
