### ISSUE TITLE
HacktoberFest Challenge Issue

### ISSUE THREAD

**Issue by sahilbansal17** [sahilbansal17/Competitive_Coding#471]
Hi friends, since many of you are starting to contribute for [Hacktoberfest](https://hacktoberfest.digitalocean.com).

To not disallow beginners to contribute to the project, this issue can be taken up by anyone starting to learn data structures and algorithms.

You need to start solving the problems in the Hackerrank's Tracks and add your solutions in the branch named **trackname** in a new folder with your github username.

For example, if I am solving the problems in the **Interview Preparation Kit** [here](https://www.hackerrank.com/interview/interview-preparation-kit), then there is a branch in the project with the name **interview_preparation_kit**, so I will create a folder in that named **sahilbansal17** and start adding the solutions in that folder.

In every pull request, at least 4 solutions should be there. We will mark invalid all those pull requests having less than 4 solutions.

Make sure that your solutions are well commented, do not use any macros, quite readable, properly indented and organized in proper folders (if the track has any categorization, for e.g. interview preparation kit has separate topics like Arrays, Sorting, etc. so folders with these name can be created inside your folder in the branch.

**Note**: If the branch doesn't exist for the track you wish to contribute (say, [problem solving](https://www.hackerrank.com/domains/data-structures?filters%5Bstatus%5D%5B%5D=unsolved&badge_type=problem-solving), then comment in the issue. The branch will be created.

**Comment by Knightrv** [comment]
I am a newbie in open source and I would like to contribute.
I am planning to solve the Linked List section of hackerrank interview preparation kit.
May I?

**Comment by sahilbansal17** [comment]
Sure @Knightrv Follow the guidelines mentioned above.

**Comment by anmolagarwal999** [comment]
I am new to open source and want to contribute to this project.
Do I need to solve atleast 4 problems and upload their codes here for a valid pull request ?
Can I contribute to this project ?

**Comment by sahilbansal17** [comment]
Sure @anmolagarwal999 
Please solve at least 4 problems in one pull request.

**Comment by anmolagarwal999** [comment]
Can I solve 4 problems on codeforces and then upload the code here ?

**Comment by soniaabhyankar** [comment]
Hey, can you create a branch for the track Problem Solving?

**Comment by sahilbansal17** [comment]
Sure @soniaabhyankar. Done!

**Comment by anuragpatro** [comment]
Hey, so this is my first time doing Hacktoberfest so I'm just confirming what I should do, I'll upload 4 files into 'Codechef' in the branch problem-solutions in the particular folder, mine being 'October Challenge 2019' and then send a pull request, that's it right?

**Comment by sahilbansal17** [comment]
No @anuragpatro This issue is for working on Hackerrank's trackwise problems and adding it in the corresponding branch. If you wish to contribute the October challenge problems, directly contribute in the master branch and send a PR.
