### ISSUE TITLE
Sorting algorithms.

### ISSUE THREAD

**Issue by shivhek25** [sahilbansal17/Competitive_Coding#48]
- [x] Selection sort
- [x] Bubble Sort
- [x] Merge Sort
- [x] Counting sort
- [x] Heap Sort
- [x] Quick Sort
- [x] Radix Sort
- [x] Bucket Sort

**Comment by dhairyabaweja** [comment]
I wish to contribute to this issue. Can I contribute @sahilbansal17 ?

**Comment by sahilbansal17** [comment]
@dhairyabaweja Have you not gone through the guidelines in [GSSoC wiki page](https://github.com/sahilbansal17/Competitive_Coding/wiki/GSSoC) ?

**Comment by shivhek25** [comment]
Should I add all the possible sorting algorithms in one subdirectory itself or do it one by one in separate issues ? @sahilbansal17

**Comment by dhairyabaweja** [comment]
I m sorry did I miss anything in the guidelines? @sahilbansal17

**Comment by shivhek25** [comment]
@dhairyabaweja According to the guidelines, you cannot work on an issue if someone else is already working on it. Since I opened the issue and I mentioned that I wish to work on it, I get a time span of 1-2 days to work on the issue and create a PR. If I dont, then the issue becomes available to you (or whoever comments first).

**Comment by dhairyabaweja** [comment]
@shivhek25 I got it. Sorry for the inconvenience.

**Comment by shivhek25** [comment]
@dhairyabaweja Chill, its not an inconvenience on my part at all. :)
All the best !

**Comment by sahilbansal17** [comment]
@shivhek25 Just create a list of all sorting algorithm in this issue as sub-tasks as some other issues had it. Work on one at a time.

**Comment by jstjyoti** [comment]
Can I explain heap sort in my own way and why is it better to use can I explain with my document?

**Comment by shivhek25** [comment]
Okay. I have added the list. Will points be given as 10 (cakewalk type) per algorithm or 10 points for the whole issue ?
@sahilbansal17

**Comment by jstjyoti** [comment]
Hello Mentor,
I would suggest you to keep marking as 10 points per algorithm.

Thank you.

**Comment by sahilbansal17** [comment]
@jstjyoti Yes, you can start working on *Heap Sort*.

**Comment by sahilbansal17** [comment]
@shivhek25 @jstjyoti Please don't worry about the points. They would be given as per your work. Just keep learning and improving!

**Comment by sahilbansal17** [comment]
Last 3 sorting algorithms are yet to be claimed.

**Comment by Anjali2901** [comment]
Can I work on Bucket Sort Algorithm ?

**Comment by sahilbansal17** [comment]
Yes sure. @Anjali2901

**Comment by jstjyoti** [comment]
Can I work on Quick Sort?

**Comment by lavishsaluja** [comment]
Okay, Radix Sort then.
@jstjyoti Actually, It's almost done. https://github.com/sahilbansal17/Competitive_Coding/pull/140

**Comment by lavishsaluja** [comment]
Not working on Radix. Up for Grabs!

**Comment by CoderJolly** [comment]
pls assign radix sort and pls mention wich lang...

**Comment by shikher-raj** [comment]
Can i work on radix sort?

**Comment by sahilbansal17** [comment]
@CoderJolly You can start working on radix sort. Use whichever language you prefer.

**Comment by sahilbansal17** [comment]
@shikher-raj You can take up some other issue or create one for yourself following the guidelines in the [GSSoC wiki page](https://github.com/sahilbansal17/Competitive_Coding/wiki/GSSoC).

**Comment by shivhek25** [comment]
Can I take up radix sort ?

**Comment by sahilbansal17** [comment]
@shivhek25 Take up one issue at a time.

**Comment by h-sinha** [comment]
Is someone working on radix sort?

**Comment by h-sinha** [comment]
@shivhek25 are you working on radix sort?

**Comment by sahilbansal17** [comment]
@h-sinha You can start working on it.
