### ISSUE TITLE
Binary Search Tree

### ISSUE THREAD

**Issue by dhairyakhale** [sahilbansal17/Competitive_Coding#49]
- [x] Insertion, Deletion, Traversal, Search 
- [x] LCA Construction
- [ ] Height related operations

**Comment by dhairyakhale** [comment]
@sahilbansal17 does it have to include all insertion, deletion, traversal, reversal, search?

**Comment by sahilbansal17** [comment]
@dhairyakhale Since you issue only mentions traversal, I guess you are interested in implementing that only at the moment.

**Comment by dhairyakhale** [comment]
But I'll have to include code for insertion in my program anyway, as I'll have to create a tree before traversing through it. If you want me to assign only traversal, I'll only explain the code of traversal and not of insertion. Will that be okay?

**Comment by sahilbansal17** [comment]
@dhairyakhale This is a self created and self-assigned issue, so you can work on as much possible. Try to make issue headings more clear and general. You can create sub-task lists inside the issue and complete each of them.

**Comment by sahilbansal17** [comment]
Also, we have created this Wiki for [Data Structures](https://github.com/sahilbansal17/Competitive_Coding/wiki/Data-Structures) just to help you create better issues and work on them. It already contains what all sub-tasks should be there for Binary Trees and BST.

**Comment by dhairyakhale** [comment]
Okay I'll cover all the four sub-tasks.

**Comment by shiv07tiwari** [comment]
I would like to work on the second part of this issue ! @sahilbansal17

**Comment by iamkaustubh1019** [comment]
I will also like to work on this issue.

**Comment by sahilbansal17** [comment]
@dhairyakhale It has been two days. Please finish ASAP. 
@shiv07tiwari @iamkaustubh1019 Please discuss amongst each other and choose either of the sub-tasks 2 or 3.

**Comment by shiv07tiwari** [comment]
@iamkaustubh1019  Can i start working on second issue while you work on the third issue ?

**Comment by sahilbansal17** [comment]
@shiv07tiwari You can start working on the 2nd sub-task.

**Comment by sahilbansal17** [comment]
@shiv07tiwari Not just height, you need to add functions for more similar operations, like **diameter** of the tree, and also the **Least common ancestor**.

**Comment by mohitj27** [comment]
is the 2nd task still available if yes i want to work on this

**Comment by sahilbansal17** [comment]
@mohitj27 Take up either this issue or the Disjoint set.

**Comment by mohitj27** [comment]
okk first i will do disjoint set issue and after that this
