### ISSUE TITLE
Fork Badge Not Updating 

### ISSUE THREAD

**Issue by harshraj22** [sahilbansal17/Competitive_Coding#498]
The fork badge in [README.md](https://github.com/sahilbansal17/Competitive_Coding/blob/master/README.md) is not getting updated automatically . 
  
![Screenshot from 2019-10-07 12-25-55](https://user-images.githubusercontent.com/46635452/66290911-16996680-e8fe-11e9-87b4-fbd5a8db0323.png)

**Comment by sahilbansal17** [comment]
@harshraj22 Can you please find the bug and update the README?

**Comment by harshraj22** [comment]
The issue was created due to error from shield.io side and is expected to be sorted out soon. [Reference](https://github.com/badges/shields/issues/4149)

**Comment by harshraj22** [comment]
Badge is updated. Closing issue.
