### ISSUE TITLE
Disjoint Set Union

### ISSUE THREAD

**Issue by dhairyabaweja** [sahilbansal17/Competitive_Coding#50]
- [ ] Basic operations and complexity analysis [working : @mohitj27 ]
- [ ] Use in Graphs and related problems 
- [ ] Path compression and Union by rank
- [ ] Complexity analysis (Advanced)

**Comment by dhairyabaweja** [comment]
I want to add the basic operations and include the complexity analysis. @sahilbansal17 ?

**Comment by dhairyabaweja** [comment]
I m not working on any other issue presently. @sahilbansal17

**Comment by mohitj27** [comment]
can i start working of this if something remaining in this

**Comment by sahilbansal17** [comment]
Yes @mohitj27 All the sub-tasks are available.

**Comment by mohitj27** [comment]
means nothing is merged yet

**Comment by sahilbansal17** [comment]
@mohitj27 Yes.
