### ISSUE TITLE
Plagiarism checker on Pull Requests

### ISSUE THREAD

**Issue by sahilbansal17** [sahilbansal17/Competitive_Coding#504]
This repository is getting a lot of PRs where the code is being copied from Geeksforgeeks or other platforms.

It would be nice if we can use some Plagiarism checker API or make a custom tool to see if the PR's code is copied from somewhere by checking some of the keywords along with the code.

For. eg. a code of **binary search** can be compared with similar codes on GFG, HackerEarth, etc. and a plagiarism score can be assigned to the PR.

**Comment by puthusseri** [comment]
> This repository is getting a lot of PRs where the code is being copied from Geeksforgeeks or other platforms.
> 
> It would be nice if we can use some Plagiarism checker API or make a custom tool to see if the PR's code is copied from somewhere by checking some of the keywords along with the code.
> 
> For. eg. a code of **binary search** can be compared with similar codes on GFG, HackerEarth, etc. and a plagiarism score can be assigned to the PR.

Could you please explain how can we implement this concept.

**Comment by sahilbansal17** [comment]
> > This repository is getting a lot of PRs where the code is being copied from Geeksforgeeks or other platforms.
> > It would be nice if we can use some Plagiarism checker API or make a custom tool to see if the PR's code is copied from somewhere by checking some of the keywords along with the code.
> > For. eg. a code of **binary search** can be compared with similar codes on GFG, HackerEarth, etc. and a plagiarism score can be assigned to the PR.
> 
> Could you please explain how can we implement this concept.

@puthusseri I am also not completely sure about it. We need to see if there are any Open APIs related to this that can help.

**Comment by harshraj22** [comment]
[This](https://github.com/codeclassroom/PlagCheck) might help, though I am not sure how to automate this for pr (but for plagarisms we can have codes from popular websites stored locally rather than scrapping every time a pr is made and then checking for plagarism). let me know if you have some suggestions on how to automate this thing for pr. The issue seems very interesting and I want to work on it.
