### ISSUE TITLE
Add OCT19B CodeChef solutions

### ISSUE THREAD

**Issue by KruZZy** [sahilbansal17/Competitive_Coding#539]
Add solutions to the OCT19B contest problems on CodeChef:

- [x] S10E
- [x] SAKTAN
- [x] MARM 
- [ ] MSV
- [ ] EVEDG
- [ ] MSNG
- [ ] MAXLIS
- [ ] BACREP

**Comment by TheAlakazam** [comment]
Can I work on this?

**Comment by sahilbansal17** [comment]
Sure, Both of you @KruZZy and @TheAlakazam can work on it since there are many different problems in this contest.
