### ISSUE TITLE
Lower Bound, Upper Bound 

### ISSUE THREAD

**Issue by shivhek25** [sahilbansal17/Competitive_Coding#55]
- [x] Lower Bound algorithm
- [x] Upper Bound algorithm

**Comment by shivhek25** [comment]
- [ ] Lower Bound algorithm
- [ ] Upper Bound algorithm

**Comment by pritamnegi** [comment]
What has to be exactly done in this issue??

**Comment by shivhek25** [comment]
@sahilbansal17 I have the programs ready but I haven't pushed them because of the other issue.
