### ISSUE TITLE
Different LinkedList reversing Techniques

### ISSUE THREAD

**Issue by Anujg935** [sahilbansal17/Competitive_Coding#57]
In LinkedList, many algorithms require to reverse the linked list.so it's the building block of many algorithms. I want to make 4 different methods of reversing the LinkedList some are recursive and some are iterative all have different complexity.
This helps students to learn about how to tackle the reversing problem of  LinkedList.
**Following are the different approaches:-**
**1. Recursive:-**
    - Simple recursion (**Time Complexity O(n^2)**)
    - Recursion Double Node (**Time Complexity O(n)**) this is to get to know students about the mix of data structures and oops concepts.
    - Recursion Best Method (**Time Complexity O(n)**)

**2. Iterative:-** 
     -This is for those who are not comfortable with recursion (Time Complexity O(n))

After learning these 4 approaches students gets the complete knowledge about Reversing the linked list.
I can also make the article or blog regarding this to make these approaches easy to understand.

Please assign me this issue so that i can start working on this. If there is any suggestion please give it to me.
Thanks.

**Comment by imkaka** [comment]
Please assign it to me.

**Comment by sahilbansal17** [comment]
@imkaka Please go through the [GSSoC wiki page](https://github.com/sahilbansal17/Competitive_Coding/wiki/GSSoC). Only one person can work on an issue at a time!

**Comment by Anujg935** [comment]
I will also add the insert and print function of the linkedlist in this
