### ISSUE TITLE
Hashmap Implementation

### ISSUE THREAD

**Issue by bscoolcoder** [sahilbansal17/Competitive_Coding#58]
C++ code for:
Inserting a key in map
Searching for a key 
Removing a key from map

**Comment by bscoolcoder** [comment]
I will work on above issue

**Comment by adi44** [comment]
i would like to impliment Hashmap

**Comment by sahilbansal17** [comment]
@adi44 This issue is already claimed by @bscoolcoder . Please read the [GSSoC Wiki page](https://github.com/sahilbansal17/Competitive_Coding/wiki/GSSoC) if you haven't already.

**Comment by sahilbansal17** [comment]
@bscoolcoder It has been 2 days. If you don't submit a PR today, it can be claimed by others.

**Comment by bscoolcoder** [comment]
I will submit a PR by today.
