### ISSUE TITLE
n-th Fibonacci number in O(log n), diameter of a tree & IDDFS

### ISSUE THREAD

**Issue by KruZZy** [sahilbansal17/Competitive_Coding#592]
Hello! I would like to work on the following:

- [x] computing the n-th Fibonacci number in O(log n) 
- [x] diameter of a tree 
- [x] iterative deepening depth first search (IDDFS)

Had some problems and couldn't contribute for a time, but I want to continue contributing.

**Comment by sahilbansal17** [comment]
Sure @KruZZy Sounds great.

**Comment by KruZZy** [comment]
Added all of the above.
