### ISSUE TITLE
Method of dynamic programming

### ISSUE THREAD

**Issue by monsij** [sahilbansal17/Competitive_Coding#60]
Being of the most valuable tool for problem-solving, I would like to contribute a code base for many problems where they can be applied as referred to in [Algorithms](https://github.com/sahilbansal17/Competitive_Coding/wiki/Algorithms) .

- [x] Traveling Salesman Problem
- [x] Longest Increasing Subsequence
- [x] Rod Cutting Problem
- [ ] Coin change problem
- [ ] Matrix Chain multiplication
- [x] Max 1D Range Sum
- [ ] Max 2D Range Sum
- [x] Longest Common Subsequence 
- [x] Longest Repeated Subsequence
- [ ] Edit distance

**Comment by sahilbansal17** [comment]
@monsij Sure, make a list of sub-tasks in the issue description in the following manner.
- [ ] Sub-task 1
- [ ] Sub-task 2

**Comment by pritamnegi** [comment]
I want to contribute code for Longest Common Subsequence

**Comment by monsij** [comment]
Can I add topics under than dynamic programming other than those mentioned in [Algorithms]? @sahilbansal17  @ramitsawhney27 (https://github.com/sahilbansal17/Competitive_Coding/wiki/Algorithms)

**Comment by sahilbansal17** [comment]
Yes.

**Comment by frost-queen** [comment]
I want to work on matrix chain multiplication.Can I proceed?

**Comment by sahilbansal17** [comment]
@frost-queen Yes, sure.

**Comment by jstjyoti** [comment]
can i work on matrix chain multiplication ordering?

**Comment by pritamnegi** [comment]
I wish to work on Coin change problem. Can I proceed??

**Comment by imkaka** [comment]
@sahilbansal17 I want to work on Matrix Chain Multiplication Please assign it.
