### ISSUE TITLE
Error in template

### ISSUE THREAD

**Issue by harshraj22** [sahilbansal17/Competitive_Coding#614]
https://github.com/sahilbansal17/Competitive_Coding/blob/1403a763003397ef2f41baac8a7d19f958f16f76/cpp/array_helper.cpp#L20

The last argument in `accumulate` (i.e. 0 in this case) should have same data type as that of array. So the following code fails (gives compilation error)
```c++
vector<long long int> v = {1, 3};
cout << accumulate(v.begin(), v.end(), 0) << '\n';
```

while the following passes
```c++
vector<long long int> v = {1, 3};
cout << accumulate(v.begin(), v.end(), 0LL) << '\n';
```

In template, we are accepting the type of elements that vector contains, but using accumulate as if vector contains only integers.

**Comment by sahilbansal17** [comment]
@harshraj22 Oh, got it, thanks for pointing this out, can you find a fix for this?

**Comment by harshraj22** [comment]
Somehow the template seems to be working, which I can't figure out why. Hence closing.
