### ISSUE TITLE
MergeSort In linkedList

### ISSUE THREAD

**Issue by Anujg935** [sahilbansal17/Competitive_Coding#74]
In LinkedList data structure it becomes very difficult to sort it and further with a very good time complexity.MergeSort has good time complexity but for learners or students, it becomes very difficult to implement it in LinkedList. I will make 2-3 different functions to make students/learners understand different algorithms and finally use these functions in mergeSort.Therefore,
The following are the subtasks Of MergeSort are:-
- [x] Midpoint Of linked List Function (Without finding the length of LinkedList means fast operation)(@Anujg935 )
- [x] Merging 2 sorted LinkedList
- [x] MergeSort (Using above 2 functions )

Students Will get to know about many aspects on how too work on LinkedList by seeing this code.

Please assign this issue to me such that I can start working on it. If you have any suggestions to further improve it then please give.
Thanks.

**Comment by aditya81070** [comment]
@Anujg935  you can start working on this.

**Comment by Anujg935** [comment]
please have a look at code
