### ISSUE TITLE
Segment Tree

### ISSUE THREAD

**Issue by Sameeksha7** [sahilbansal17/Competitive_Coding#75]
- [ ] Basics
- [ ] Complexity Analysis

**Comment by aditya81070** [comment]
@Sameeksha7  Please add subtask
### task1
- Basics
### task2
- Complexity Analysis

**Comment by aditya81070** [comment]
@Sameeksha7  You can work on it.

**Comment by sahilbansal17** [comment]
This issue is open.

**Comment by h-sinha** [comment]
I'll work on this
