### ISSUE TITLE
2-4 trees Implementation

### ISSUE THREAD

**Issue by ighosh98** [sahilbansal17/Competitive_Coding#79]
Implementation of basic operations and construction of the 2-4 tree.
- [ ] Insertion 
- [ ] Deletion
- [ ] Search

**Comment by ighosh98** [comment]
I would like to work on this issue @sahilbansal17

**Comment by sahilbansal17** [comment]
@aditya81070 This is for `2 - 4 Trees` which are different from `Binary Search Trees`. I think you missed the issue description.

**Comment by aditya81070** [comment]
@sahilbansal17 sorry for this. I am totally unaware of this type of tree.

**Comment by sahilbansal17** [comment]
No problem.
