### ISSUE TITLE
Construction of Graphs

### ISSUE THREAD

**Issue by dhairyakhale** [sahilbansal17/Competitive_Coding#81]
**Basics of Graph Theory**:
Construction of graphs via:
1. [ ] Adjacency List
2. [ ] Adjacency Matrix
3. [ ] Edge List

Also, provide the complexity analysis for each of them.

**Comment by dhairyakhale** [comment]
I would like to take up this issue, if it hasn't been done before.

**Comment by dhairyakhale** [comment]
I have to cover construction, basics and complexity analysis then?

**Comment by sahilbansal17** [comment]
Yup, updated the issue description.

**Comment by bscoolcoder** [comment]
Can I take this issue?

**Comment by sahilbansal17** [comment]
Yes

**Comment by bscoolcoder** [comment]
@sahilbansal17 pls assign this issue to someone else
