### ISSUE TITLE
Modified Fibonacci Sequence

### ISSUE THREAD

**Issue by ramitsawhney27** [sahilbansal17/Competitive_Coding#82]
Defining the modified Fibonacci sequence as:

_F(n) = F(n-1) + 2F(n-2) + 3F(n-3)_
where, F(0) = 0, F(1) = 1, F(2) = 3

The following tasks have to complete for an entire score:
1. Write a function to return the nth modified Fibonacci number in less than O(n) time.
2. Write a function to print the first n modified Fibonacci numbers in O(n) time. 
3. Clearly explain your solution, with proofs for how you arrived at the time complexities.

**Comment by ighosh98** [comment]
I would like to work on this @ramitsawhney27 .

**Comment by lavishsaluja** [comment]
Working on this!

**Comment by ramitsawhney27** [comment]
@ighosh98 go ahead.

**Comment by lavishsaluja** [comment]
Aren't you already working on https://github.com/sahilbansal17/Competitive_Coding/issues/79? @ighosh98

**Comment by ramitsawhney27** [comment]
As per policy, we can have only one student working on one issue. @lavishsaluja you can work on this.

**Comment by ramitsawhney27** [comment]
@lavishsaluja It's been 3 days, other students have been pinging me as well. Post 6 PM today, I'll make this accessible for anyone to send a PR to, and the quickest correct answer will get the points.

**Comment by ramitsawhney27** [comment]
@ighosh98 please feel free to start working on this.
