### ISSUE TITLE
Pair sum problem in a Tree

### ISSUE THREAD

**Issue by ramitsawhney27** [sahilbansal17/Competitive_Coding#83]
Given a balanced binary search tree (take a sample tree in your code) and a number x, your task is to determine if there exists a pair of nodes, such that their sum is equal to x. Every node contains a value, left ptr and right ptr. 

The following tasks need to be done for an entire score:
1. Return the larger of the two numbers if there exists a pair, else -1 in time O(n).
2. Space taken should be less than O(n).
3. Explanations for all methods and time/space complexities.

**Comment by sourabh1031** [comment]
@ramitsawhney27 I will take up the issue

**Comment by ramitsawhney27** [comment]
@sourabh1031 go ahead.

**Comment by sourabh1031** [comment]
@ramitsawhney27 actually this can be done by two methods do i need to write both methods

**Comment by Dhiraj240** [comment]
@sahilbansal17 @ramitsawhney27 can i work on this issue.Is everyone allowed to submit PR for the challenged label issues?

**Comment by sahilbansal17** [comment]
Yes

**Comment by CoderJolly** [comment]
@sahilbansal17 is it still open?

**Comment by ramitsawhney27** [comment]
@CoderJolly yes.

**Comment by CoderJolly** [comment]
pls assign it to me......

**Comment by sahilbansal17** [comment]
This is a challenge problem, so whosoever finishes it first and sends a PR, will get the points. So, no one needs to be assigned to this.

**Comment by CoderJolly** [comment]
where shall i save the file of .cpp solution?

**Comment by sahilbansal17** [comment]
@CoderJolly [here](https://github.com/sahilbansal17/Competitive_Coding/blob/master/Challenge%20Problems%20-%20GSSoC/pair_sum_problem_BST.cpp)

**Comment by tanvi15** [comment]
Managed time complexity of O(nlogn) and space O(1), but I guess that's not permissible?

**Comment by ramitsawhney27** [comment]
@tanvi15 considering this is the first and so far only problem for 50 points, not really. Let me know your approach though, I can help out if you're close.

**Comment by tanvi15** [comment]
@ramitsawhney27 I did an inorder traversal, and kept searching for (k - nodeData) for each nodeData. If present, their sum is k and function returns k-nodeData (right side is greater)

**Comment by CoderJolly** [comment]
@ramitsawhney27 its my first problem too....if my submission is permissible, pls award me points first

**Comment by tanvi15** [comment]
@ramitsawhney27 yes I was trying to do the same

**Comment by ramitsawhney27** [comment]
Closing this now, the issue has been solved.

**Comment by tanvi15** [comment]
@h-sinha great work, man!

**Comment by h-sinha** [comment]
Thanks @tanvi15
