### ISSUE TITLE
Finding the GCD of 2 numbers

### ISSUE THREAD

**Issue by Anujg935** [sahilbansal17/Competitive_Coding#85]
Greatest Common Divisor is one of the important algorithms in number theory it is used in many problems like prime numbers, cryptography etc.
I will make 2 algorithms for finding gcd of two numbers:-
- [x] Naive Algorithm (simplest approach) but very poor time complexity
- [x] Euclid's Algorithm (very fast approach)

please assign it to me so that I can start working on it as soon as possible.

**Comment by ramitsawhney27** [comment]
Sure go ahead.
