### ISSUE TITLE
Coin problem

### ISSUE THREAD

**Issue by Aashu24** [sahilbansal17/Competitive_Coding#87]
Greedy Algorithm to find the minimum number of coins

Given a value V, if we want to make change for the amount V and we have infinite supply of each of the denominations in some currency say {1,2,5,10,20,50} (which will be taken as input from the user} valued coins/notes, what is the minimum number of coins and/or notes needed to make the change?

I will be implementing this algorithm in Java. Please assign it to me so that I can start working on it as soon as possible.

**Comment by ramitsawhney27** [comment]
If you want points for this problem, it should have both the dp and greedy solution and a convincing answer for why and when the greedy algorithm works.
