### ISSUE TITLE
Backtracking - N queen problem

### ISSUE THREAD

**Issue by tanvi15** [sahilbansal17/Competitive_Coding#92]
Placing N chess queens on an N×N chessboard so that no two queens can attack each other.

**Comment by ramitsawhney27** [comment]
1. Start with this once your MST PR is accepted.
2. Modify this such that a queen can only attack a queen if it's in the range diagonally by 5 blocks, horizontally by 4 blocks and vertically by 3 blocks.

**Comment by Sandip75** [comment]
Can I work on it?
