### ISSUE TITLE
Breaking a number into primes

### ISSUE THREAD

**Issue by ramitsawhney27** [sahilbansal17/Competitive_Coding#93]
Given: 
A positive integer n > 1.

Tasks:
1. Print a list of primes such that their sum is equal to n, maximize the number of primes in this list.
2. Add proper explanations and time complexity.

Samples:
2 - 2
4 - 2+2

**Comment by moulikcipherX** [comment]
We have to return no of primes to get sum or the digits also.

**Comment by ramitsawhney27** [comment]
Return the digits too.
This is now completed by @h-sinha.
