### ISSUE TITLE
Islands in a Graph

### ISSUE THREAD

**Issue by ramitsawhney27** [sahilbansal17/Competitive_Coding#94]
Given:
A grid of size n x m. Each cell is either Red or Blue. Red is denoted as * and . as Blue.
The entire grid is surrounded in blue.
A collection of blue cells surrounded by red on all sides is considered a pool. 

Tasks:
1. Count the total number of pools in the grid.
2. Return the size of each of the pools in the grid.
3. Time and Space complexities for each of these operations.

Sample:
5 4

\****
\*..*
\****
\*.**
\..**

Number of pools: 1; size = 2

**Comment by moulikcipherX** [comment]
I think 4th row is incomplete

**Comment by h-sinha** [comment]
@ramitsawhney27 it would be really helpful if you update the fourth line of the test case

**Comment by ramitsawhney27** [comment]
@h-sinha @moulikcipherX fixed.

**Comment by h-sinha** [comment]
Shouldn't the number of pools be 1 in this case? As the '.' in 4th row has a '.' on one side.

**Comment by ramitsawhney27** [comment]
The two pools are in row 2 and row 4 of size 2 and 1 respectively. The one in the 5th row is not counted.

**Comment by lavishsaluja** [comment]
@ramitsawhney27 Will like to work on this!

**Comment by tanvi15** [comment]
Yeah I meant to ask whether it has been solved already or not

**Comment by ramitsawhney27** [comment]
Not yet

**Comment by ramitsawhney27** [comment]
I just realized, markdown messes up how it's being shown. Something to do with the \ and *. I've edited it. Ideally, the . should be on the 3rd column in the 4th row. Then the solution is correct for what was given previously.

**Comment by tanvi15** [comment]
Okay, and diagonally blue is okay for a pool?

**Comment by ramitsawhney27** [comment]
Just keep it as up down left right (4-connectivity) for simplicity.

**Comment by ramitsawhney27** [comment]
This is solved, closing it.
