### ISSUE TITLE
Tower Of Hanoi Problem

### ISSUE THREAD

**Issue by Anujg935** [sahilbansal17/Competitive_Coding#95]
In recursion Tower of Hanoi problem is very much important and gives the students a very good knowledge about how actually the recursion works.
Please assign it to me.

**Comment by ramitsawhney27** [comment]
Sure, so you get a good idea of how it works let's make some modifications:
1. Solve it iteratively.
2. Add time complexity analysis.
3. Solve the problem with the modification that you can not directly transfer any disk from the starting peg to the final peg without using the auxiliary peg.

Good luck!

**Comment by ramitsawhney27** [comment]
Solve the standard problem iteratively without any modification.
Solve the modified problem recursively.

**Comment by sahilbansal17** [comment]
@Anujg935 Please start working on it soon.

**Comment by Anujg935** [comment]
It's almost done only one or two things are left
